// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFP3q13jEqN_UT8zXayACLRcNx3WlKRQ0',
    appId: '1:764599041372:web:675a64e6697744f6a49599',
    messagingSenderId: '764599041372',
    projectId: 'gdgc-app',
    authDomain: 'gdgc-app.firebaseapp.com',
    storageBucket: 'gdgc-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqMj3x2FpTA26SYTKdD7YxCswJLjteN7U',
    appId: '1:764599041372:android:9ff54e565dd0092ea49599',
    messagingSenderId: '764599041372',
    projectId: 'gdgc-app',
    storageBucket: 'gdgc-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8Nm5TheH4tXzF4rE_D_00l-Qd_Sd7URI',
    appId: '1:764599041372:ios:65d8b43cd910d359a49599',
    messagingSenderId: '764599041372',
    projectId: 'gdgc-app',
    storageBucket: 'gdgc-app.firebasestorage.app',
    iosBundleId: 'com.example.gdgcApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8Nm5TheH4tXzF4rE_D_00l-Qd_Sd7URI',
    appId: '1:764599041372:ios:65d8b43cd910d359a49599',
    messagingSenderId: '764599041372',
    projectId: 'gdgc-app',
    storageBucket: 'gdgc-app.firebasestorage.app',
    iosBundleId: 'com.example.gdgcApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFP3q13jEqN_UT8zXayACLRcNx3WlKRQ0',
    appId: '1:764599041372:web:d4619fbf3027736da49599',
    messagingSenderId: '764599041372',
    projectId: 'gdgc-app',
    authDomain: 'gdgc-app.firebaseapp.com',
    storageBucket: 'gdgc-app.firebasestorage.app',
  );
}
